### ISSUE TITLE
Change project name to be Fixiversity

### ISSUE THREAD

**Issue by ericm** [fixiversity/fixiversity#9]
## Story Summary

As a `development team member` I want to `change the app name from edu-change to be our new app name - Fixiversity` so that `all users and team members can see our cool new app name`

## Background
The name of edu-change is not unique and so we come up with `Fixivisity`.

## ToDo

  - [ ] Tests
  - [ ] Is the performance acceptable? 
  - [ ] Manual Testing
  - [ ] Code Reviewed

## Acceptance Criteria
- [ ] All edu-change changed to be Fixiversity
- [ ] Take care of both code base and UI

## Definition of Done
```
All code delivered and managed in GIT
Code is globalization ready - strings externalized
Code meets accessibility standards
Project management notified of any 3rd party/open source updates
Impact on other services is understood and impacted teams engaged 
```
